"""add_clerk_user_id_to_users

Revision ID: 065672879799
Revises: 9c15b2f0f536
Create Date: 2025-11-20 09:18:31.061488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065672879799'
down_revision = '9c15b2f0f536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing users
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)

    # Set default value for existing users (they'll need to re-authenticate with Clerk)
    # We'll use their email as a temporary placeholder that will be updated when they sign in
    op.execute("UPDATE users SET clerk_user_id = 'legacy_' || id::text WHERE clerk_user_id IS NULL")

    # Now make it non-nullable
    op.alter_column('users', 'clerk_user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###
