"""add_location_id_to_oauth_tokens

Revision ID: 734b4cb9cb59
Revises: 065672879799
Create Date: 2025-11-20 15:05:14.060450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734b4cb9cb59'
down_revision = '065672879799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_oauth_tokens_location_id'), 'oauth_tokens', ['location_id'], unique=False)
    op.create_foreign_key('oauth_tokens_location_id_fkey', 'oauth_tokens', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oauth_tokens_location_id_fkey', 'oauth_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_oauth_tokens_location_id'), table_name='oauth_tokens')
    op.drop_column('oauth_tokens', 'location_id')
    # ### end Alembic commands ###
