"""add_gbp_location_name_to_locations

Revision ID: 84544e62248c
Revises: a26a3c88bbd3
Create Date: 2025-11-19 00:56:40.666185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84544e62248c'
down_revision = 'a26a3c88bbd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('gbp_location_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'gbp_location_name')
    # ### end Alembic commands ###
