"""add_agent_tasks_and_outputs_tables

Revision ID: a26a3c88bbd3
Revises: 0ddcd8d03b35
Create Date: 2025-11-18 19:00:32.752134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a26a3c88bbd3'
down_revision = '0ddcd8d03b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.Enum('CREATE_GBP_POST', 'RESPOND_TO_REVIEW', 'UPDATE_BUSINESS_HOURS', 'CREATE_BLOG_POST', 'UPDATE_BLOG_POST', 'CREATE_SOCIAL_POST', 'CREATE_CITATION', 'UPDATE_CITATION', 'RESEARCH_KEYWORDS', 'TRACK_RANKINGS', name='agenttasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', 'REJECTED', 'POSTED', 'FAILED', name='agenttaskstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('output_type', sa.Enum('GBP_POST', 'BLOG_POST', 'SOCIAL_POST', 'CITATION', 'REVIEW_RESPONSE', 'KEYWORD_REPORT', name='outputtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SCHEDULED', 'POSTED', 'FAILED', name='outputstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Enum('BOOK', 'ORDER', 'SHOP', 'LEARN_MORE', 'SIGN_UP', 'CALL', name='gbpcalltoaction'), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('platform_url', sa.String(length=1000), nullable=True),
    sa.Column('performance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_outputs')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
